### PR TITLE
Adding group 3 questions, fixed photo link, now working

### PR DESCRIPTION
**Pull request by JuanC513**

### CODE REVIEW

**Comment by fredyballest** [comment]
Please resolve the conflicts !! :)

**Comment by fredyballest** [comment]
@lauubetancourt @JuanC513 @JuanC513 @Ulvenforst @puyojulian  Guys please resolve the conflicts

**Comment by puyojulian** [comment]
Hi @fredyballest , please check if the merge can be done now. Thanks in advance.

**Review by fredyballest — APPROVED** [review]
LGTM

**Comment by fredyballest** [comment]
Hi @puyojulian @JuanC513 @Ulvenforst @lauubetancourt Testing checks have failed https://github.com/fredyunivalle/michinglishapp/actions/runs/11597667940/job/32308578629?pr=28

**Comment by puyojulian** [comment]
Hi, Teacher @fredyballest. I've corrected the issue with the test. It was an letter not matching with the intended letter casing, we apologize for that.

**Pull request merged**
